<a href="https://colab.research.google.com/github/manjunathgudditi/python-libs/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

---
## 1. HOME
* Numerical python
* python library
* used for working with arrays

***
## 2. Intro
* It also has functions for working in domain of linear algebra, fourier transform, and matrices.
* created in 2005 by Travis Oliphant
* It's an open source project

### why numpy?
* python lists are slow
* numpy array obj is 50x faster than lists
* array obj is called **ndarray**
  * has so many methods
* Arrays are very frequently used in data science, where speed and resources are very important.

> **Data Science**: is a branch of computer science where we study **how to store, use and analyze data for deriving information from it**.

### Why is NumPy Faster?
*  arrays are stored at one continuous place in memory
  * so processes can access and manipulate them very efficiently
  * this behavior is called locality of reference in computer science

### Which Language is NumPy written in?
* written partially in Python
* but most of the parts that require fast computation are written in C or C++.

> source code for NumPy is located at this github repository https://github.com/numpy/numpy

> github: enables many people to work on the same codebase.

___

## 3. Getting Started

### Installation
> pip install numpy

### Import NumPy


In [1]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


### NumPy as np
* NumPy is usually imported under the np alias.

Create an alias with the as keyword while importing

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4 ,5])
print(arr)

[1 2 3 4 5]


### Checking NumPy Version

In [3]:
print(np.__version__)

2.0.2


---
## 4. Creating Arrays

### create ndarray Object
* done using the **array()** function.

In [4]:
type(arr)

numpy.ndarray

we can pass a list, tuple or any array-like object into the array() method,

In [5]:
import numpy as np
arr = np.array((1, 2, 3))
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


### Dimensions:
* A dimension in arrays is one level of array depth
> nested array: array that have arrays as their elements.

### 0-D Arrays:
* scalars
* elements


### 1-D Arrays:
* array that has 0-D arrays as its elements

### 2-D Arrays:
* array that has 1-D arrays as its elements
* often used to represent matrix or 2nd order tensors
> NumPy has a whole sub module dedicated towards matrix operations called **numpy.mat**

### 3-D arrays:
* array that has 2-D arrays (matrices) as its elements
* often used to represent a 3rd order tensor.


### Check Number of Dimensions
* **ndim** attribute



In [6]:
import numpy as np

arr = np.array(24)
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[1,2], [3,4]])
arr_3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

print(arr.ndim)
print(arr)

print(arr_1.ndim)
print(arr_1)

print(arr_2.ndim)
print(arr_2)

print(arr_3.ndim)
print(arr_3)



0
24
1
[1 2 3]
2
[[1 2]
 [3 4]]
3
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Higher Dimensional Arrays
* array can have any number of dimensions.
* When the array is created, you can define the number of dimensions by using the ndmin argument.



In [7]:
import numpy as np

arr = np.array([1,2,3], ndmin=5)

print(arr)

print(arr.ndim)

[[[[[1 2 3]]]]]
5


---
## 5. Array Indexing